---
- hosts: workers
  become: yes
  gather_facts: no
  tasks:
    - raw: docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://54.197.20.108:8080/v1/scripts/E202F6B46346AA9070D5:1470920400000:gnJnaKecWz8C5NRJiit9fciuKQ
