  - name: Start rancher master node
    ec2:
      region: "{{ aws_region }}"
      image: "{{ template }}"
      instance_type: "{{ instance_type }}"
      key_name: "{{ ssh_key }}"
      group: "{{ security_group_name }}"
#     user_data: "{{ lookup('template', '../templates/master.j2') }}"
      wait: yes
    register: master
  - debug: msg="{{ lookup('template', '../templates/master.j2') }}"	
  - debug: msg='rancher master IP is {{ item.public_ip }}'
    with_items: master.instances

  - name: Add new instance to host group
    add_host: hostname={{ item.public_ip }} groupname=master
    with_items: master.instances

  - name: Start rancher workers
    ec2:
      region: "{{ aws_region }}"
      image: "{{ template }}"
      instance_type: "{{ instance_type }}"
      key_name: "{{ ssh_key }}"
      group: "{{ security_group_name }}"
#      user_data: "{{ lookup('template', '../templates/worker.j2') }}"
      count: "{{ num_nodes }}"
      wait: yes
    register: ec2

  - name: Add new instance to host group
    add_host: hostname={{ item.public_ip }} groupname=worker
    with_items: ec2.instances

